name: Deploy Preview to Firebase Hosting on PR

on: pull_request

env:
  REACT_APP_API_KEY_GAPI: ${{ secrets.REACT_APP_API_KEY_GAPI }}
  REACT_APP_CLIENT_ID_GAPI: ${{ secrets.REACT_APP_CLIENT_ID_GAPI }}

jobs:
  build_and_preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "18"
      #     cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
        env:
          REACT_APP_API_KEY_GAPI: ${{ secrets.REACT_APP_API_KEY_GAPI }}
          REACT_APP_CLIENT_ID_GAPI: ${{ secrets.REACT_APP_CLIENT_ID_GAPI }}

      - name: Deploy Preview to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STUDYBUDDY_392C7 }}"
          projectId: studybuddy-392c7
          channelId: pr-${{ github.event.pull_request.number }} # Creates a preview channel per PR
